### ISSUE TITLE
About Inference

### ISSUE THREAD

**Issue by tszslovewanpu** [Rose-STL-Lab/LIMO#19]
The first stage is the _training_ of the VAE.
The second stage is the _training_ of the property predictor, 
1、Should the third stage be viewed as the _inference_ process?
2、Does LIMO generate molecules in this manner?
a. Get 1 input molecule from ZINC250k or MOSES, LIMO gets the lantent \( z \)
b. LIMO does 10 times optimization of \( z \)
c. LIMO uses the optimized \( z \) to generate optimized molecules

Thank you very much!

**Comment by PeterEckmann1** [comment]
Thanks for your interest! 

1. Yes, I would call the third stage the inference process, because we are no longer adjusting any model weights during that stage. However, we are still performing backpropagation to optimize z, so it might make a bit more sense to call this stage "generation" instead.

2. That is almost accurate, except for (a) we initialize the latent z from the normal distribution (instead of getting an input molecule from a dataset). z is initialized here: https://github.com/Rose-STL-Lab/LIMO/blob/main/generate_molecules.py#L25

Let me know if you have any more questions.

**Comment by tszslovewanpu** [comment]
Thank you, i still have some doubts
i、For each optimization task, LIMO generates 10k molecules in the above mannel(start with ( _z_ ) sampled from the normal distribution), so does each task has its own _encoder_(actually useless, just for training the decoder), _decoder_, and _property prediction model_?
ii、For the random generation task, does LIMO just sample ( _z_ ) and put it to the decoder to generate molecules?
Sorry to bother you with such a naiive question, thanks again!

**Comment by PeterEckmann1** [comment]
No problem!

1. That's right, we have to train the encoder, decoder, and property predictor (although we can reuse the encoder and decoder across different properties). And yes, the encoder is only useful for training the decoder, we don't use it for anything else.
2. Yes, we just sample z and then decode it.

**Comment by tszslovewanpu** [comment]
Got it, thank you!
